# Generated by Django 5.1.7 on 2025-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='destination_ip_netmask',
            field=models.CharField(blank=True, default='24', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='source_ip_netmask',
            field=models.CharField(blank=True, default='24', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='communicationfinding',
            name='destination_ip_netmask',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='communicationfinding',
            name='source_ip_netmask',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='devicefinding',
            name='ip_netmask',
            field=models.CharField(blank=True, default='24', max_length=2, null=True),
        ),
    ]
