# Generated by Django 5.2.1 on 2025-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("d3c", "0001_initial"),
        ("dcim", "0207_remove_redundant_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicefinding",
            name="article_number",
        ),
        migrations.AddField(
            model_name="software",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="softwareManufacturer",
                to="dcim.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="devicefinding",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
