# Generated by Django 5.2.1 on 2026-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3c', '0002_remove_devicefinding_article_number_and_more'),
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer', 'version'), name='software_unique', nulls_distinct=False),
        ),
    ]
