# Generated by Django 5.2.1 on 2026-03-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("d3c", "0003_software_software_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filehash",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="hash",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="mapping",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="productrelationship",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="software",
            options={"ordering": ["name", "manufacturer", "version", "id"]},
        ),
        migrations.AlterModelOptions(
            name="xgenericuri",
            options={"ordering": ["id"]},
        ),
    ]
