# Generated by Django 4.2.5 on 2023-10-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0181_rename_device_role_device_role'),
        ('ipam', '0067_ipaddress_index_host'),
        ('d3c', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='target_port',
            new_name='destination_port',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='target_device',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='target_ip_addr',
        ),
        migrations.AddField(
            model_name='communication',
            name='destination_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationForCommunications', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='communication',
            name='destination_ip_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationIPAddress', to='ipam.ipaddress'),
        ),
    ]
